### PR TITLE
Create cluster of nodes based on the value of its attribute

### PR DESCRIPTION
**Pull request by joenio**

### CODE REVIEW

**Comment by joenio** [comment]
ping

**Comment by joenio** [comment]
hi neil, is there any chance you accept this pull-request?

**Comment by neilb** [comment]
Hi, sorry I've been so tardy. I'll look at this and respond one way or other this coming week (have added it to my todo list for the coming week).

**Comment by joenio** [comment]
thank you very much!

**Comment by neilb** [comment]
Sorry I took so long on this.

**Pull request merged**
